[package]
name = "utils"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
description = "utils(dictionary) host function"

[dependencies]
reactor = { path = "../reactor" }

[lints]
workspace = true
